# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- dev

variables:
  buildConfiguration: 'Release'

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
#  - task: UseDotNet@2
#    inputs:
#      packageType: 'sdk'
#      version: '3.0.100-preview7-012821'
#      includePreviewVersions: true

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - script: dotnet test --configuration $(buildConfiguration)
    displayName: 'dotnet test $(buildConfiguration)'

- job: macOS
  pool:
    vmImage: 'macOS-latest'

  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - script: dotnet test --configuration $(buildConfiguration)
    displayName: 'dotnet test $(buildConfiguration)'

- job: Ubuntu
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - script: dotnet test --configuration $(buildConfiguration)
    displayName: 'dotnet test $(buildConfiguration)'

  - script: sudo apt-get -y install cloc && ./cloc.sh
    displayName: cloc
