# TOML config file for NetCoreBB

[System]
SystemInstalled = false
MaintenanceMode = false
DevelopmentMode = false
UnderAttackMode = false

[MySQL]
Server = "localhost"
SslMode = "Preferred"
Database = "netcorebb"
Username = "root"
Password = ""
Port = 3306
Protocol = "socket"
Other = [
    #["CertificateFile", "C:\folder\client.pfx"],
    #["CertificatePassword", "password"]
]
