# TOML config file for NetCoreBB

[System]
SystemInstalled = false
MaintenanceMode = false
DevelopmentMode = false
UnderAttackMode = false

[MySQL]
Server = "localhost"
SslMode = "Preferred"
Database = "netcorebb"
Username = "root"
Password = ""
Protocol = "socket"
Port = 3306

[MySQL.Other]
#"CertificateFile" = "C:\folder\client.pfx"
#"CertificatePassword" = "password"
