# TOML config file for NetCoreBB

[System]
SystemInstalled = false
DevelopmentMode = false
UnderAttackMode = false
MaintenanceMode = false

[MySQL]
Server = "localhost"
SslMode = "Preferred"
Database = "netcorebb"
Username = "root"
Password = ""

#Port = 3306
#Protocol = "unix"
#Other = [
#            ["CertificateFile", "C:\folder\client.pfx"],
#            ["CertificatePassword", "password"]
#        ]
